FROM centos:6.6
MAINTAINER hirokazu SUGIUCHI

# setup
RUN yum update -y
RUN yum install -y rpm-build tar patch

# ruby depends
RUN yum -y install readline-devel ncurses-devel gdbm-devel db4-devel glibc-devel gcc openssl-devel libyaml-devel libffi-devel zlib-devel

# create build user
RUN useradd -u 1000 rpmbuilder

# build
RUN mkdir -p /home/rpmbuilder/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
RUN chown rpmbuilder:rpmbuilder /home/rpmbuilder/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
WORKDIR /home/rpmbuilder/rpmbuild
ADD rubybuild.sh /home/rpmbuilder/rpmbuild/rubybuild.sh
ADD ruby.spec /home/rpmbuilder/rpmbuild/SPECS/ruby.spec
ADD ruby-version /home/rpmbuilder/rpmbuild/SOURCES/ruby-version
ADD ruby-openssl.patch /home/rpmbuilder/rpmbuild/SOURCES/ruby-openssl.patch
